blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed


app_name = 'blog'

urlpatterns = [
    # Post List View:
    path('', views.post_list, name='post_list'),

    # Class-based Post List View:
    #path('', views.PostListView.as_view(), name='post_list'),

    # Post Detail View:
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail,
         name='post_detail'),

    # Post Share View:
    path('<int:post_id>/share/',
         views.post_share,
         name='post_share'),

     # Posts by Tag View:
     path('tag/<slug:tag_slug>/',
          views.post_list,
          name='post_list_by_tag'),
     
     # Latest Posts Feed View:
     path('feed/', LatestPostsFeed(), name='post_feed'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.shortcuts import redirect


sitemaps = {
    'posts': PostSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', lambda request: redirect('blog/')),
    path('blog/', include('blog.urls', namespace='blog')),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, 
         name='django.contrib.sitemaps.views.sitemap'),

]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PublisherManager(models.Manager):

    def get_queryset(self):
        return super(PublisherManager, self).get_queryset()\
                .filter(status='published')


class Post(models.Model):

    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    votes = models.IntegerField(default=0)
    tags = TaggableManager()

    # The default manager:
    objects = models.Manager()
    # Our custom manager:
    published = PublisherManager()

    class Meta:
        ordering = ('-publish', )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])


class Comment(models.Model):
    
    id = models.AutoField(primary_key=True)
    post = models.ForeignKey(Post,  on_delete=models.CASCADE,
                                    related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ('created', )

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.db.models import Count
from .forms import EmailPostForm, CommentForm
from .models import Post, Comment
from taggit.models import Tag


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_list(request, tag_slug=None):
    posts_list = Post.published.all()
    tag = None
    
    # [CASE] Post has tags:
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts_list = posts_list.filter(tags__name__in=[tag])
    
    # Handle pagination:
    paginator = Paginator(posts_list, 3)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)

    except PageNotAnInteger:
        # If page is not an integer then deliver the first page:
        posts = paginator.page(1)

    except EmptyPage:
        # If page is out of range then deliver last page of results:
        posts = paginator.page(paginator.num_pages)

    return render(request,
                  'blog/post/list.html',
                  { 'posts': posts, 'page': page, 'tag': tag })


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,  slug=post,
                                    status='published',
                                    publish__year=year,
                                    publish__month=month,
                                    publish__day=day)

    # List of active comments for this post:
    comments = post.comments.filter(active=True)

    new_comment = None

    # [CASE] POST a new comment:
    if (request.method == 'POST'):
        # A comment was posted:
        comment_form = CommentForm(data=request.POST)
        # Comment form is valid:
        if comment_form.is_valid():
            # Create Comment object:
            new_comment = comment_form.save(commit=False)
            # Assign the current blog post to the comment:
            new_comment.post = post
            # Save the comment to the database:
            new_comment.save()
    
    # [CASE] GET request:
    else:
        comment_form = CommentForm()

    # List similar posts:
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
                        .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                            .order_by('-same_tags', 'publish')

    return render(request,
                  'blog/post/detail.html',
                  { 'post': post,
                    'comments': comments,
                    'new_comment': new_comment,
                    'comment_form': comment_form,
                    'similar_posts': similar_posts})


def post_share(request, post_id):
    # Retrieve our post by id:
    post = get_object_or_404(Post, id=post_id, status='published')
    # Used to handle success message in our template:
    sent = False

    # [CASE] POST our form data:
    if (request.method == 'POST'):
        # Form was submitted:
        form = EmailPostForm(request.POST)

        # [CASE] Form is successfully validated:
        if form.is_valid():
            # Send email sharing post title + post URL:
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends that you read \"{post.title}\""
            message = f"You can read \"{post.title}\" at:  {post_url}\n\n" \
                      f"{cd['name']}'s comments:\n\n\t{cd['comments']}" \
                      "\n\nSincerely,\n📨 EMAILBOT @ MyDjangoBlog.com 🤖"
            send_mail(subject, message, 'copev313@gmail.com', [cd['to']])
            sent = True

    # [CASE] GET our form:
    else:
        form = EmailPostForm()

    return render(request,
                  'blog/post/share.html',
                  {'post': post,
                   'form': form,
                   'sent': sent})

blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" >
<head>
    <meta charset="UTF-8" >
    <meta name="viewport"  content="width=device-width, initial-scale=1.0" >
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}"  rel="stylesheet" >
    <link href="{% static 'css/blog.css' %}"  rel="stylesheet" >
</head>

<body>
    <div class="container-lg content px-1">
        <div class="row">
            <div class="col-8">
                {% block content %}{% endblock %}
            </div>

            <!-- SIDEBAR ANNOUNCEMENTS PANEL / CARD -->
            {% include './components/sidecard.html' %}
        </div>

        <div class="row"></div>
    </div>
</body>
</html>

blog/templates/blog/components/sidecard.html
{% load blog_tags %}

<div class="col-3 card border-info rounded mt-4 ml-5 p-1 h-50">
    <div class="card-body">
        <h4 class="card-title h3 pb-2 text-success"><ins>My Django Blog</ins></h4>
        <p class="card-text">Welcome!</p>
        <p class="card-text">
            Browse around and see if you find anything you like. The posts are nonsense now, but maybe one day they won't be!
        </p>

        <p><strong>Total Posts:</strong> {% total_posts %}</p>

        <hr>

        <!--
        <div class="my-2">
            <h3 class="orange"><ins>Quick Links</ins></h3>
            <h5 class="pl-2">
                <a href="/blog" class="text-warning text-decoration-none">Home</a>
            </h5>
        </div>

        <hr>
        -->

        <div>
            <h3 class="my-2 dark-blue"><ins>Latest Posts</ins></h3>
            {% show_latest_posts 3 %}
        </div>

        <hr>

        <div class="my-2">
            <h3 class="dark-blue"><ins>Most Commented Posts</ins></h3>
            {% get_most_commented_posts 3 as most_commented_posts %}
            <ol>
                {% for post in most_commented_posts %}
                    <li class="light-blue">
                        <a  href="{{ post.get_absolute_url }}"
                            class="light-blue">
                            {{ post.title }}
                        </a>
                    </li>
                {% endfor %}
            </ol>
        </div>

        <hr>

        <div class="my-2">
            <p>
                <a href="{% url 'blog:post_feed' %}" class="purple">
                    Subscribe to my RSS feed
                </a>
            </p>
        </div>

    </div>
</div>

blog/templates/blog/post/components/pagination.html
<div class="pagination d-flex justify-content-center">
    <div class="btn-group">
        <span class="step-links">
            {% if page.has_previous %}
                <span class="m-2 px-3 py-2 badge badge-pill badge-secondary">
                    <a  class="text-light text-decoration-none"
                        href="?page={{ page.previous_page_number }}">
                        Previous
                    </a>
                </span>

            {% else %}
            <span class="invisible m-2 px-3 py-2 badge badge-pill badge-secondary">
                <div  class="text-light text-decoration-none">Previous</div>
            </span>

            {% endif %}
    
            <span class="px-3 py-1 border border-secondary border-2 rounded-pill current">
                Page {{ page.number }} of {{ page.paginator.num_pages }}
            </span>
    
            {% if page.has_next %}
                <span class="m-2 px-3 py-2 badge badge-pill badge-secondary">
                    <a  class="text-light text-decoration-none"
                        href="?page={{ page.next_page_number }}">
                        Next
                    </a>
                </span>

            {% else %}
                <span class="invisible m-2 px-3 py-2 badge badge-pill badge-secondary">
                    <div  class="text-light text-decoration-none">Next</div>
                </span>
            {% endif %}
        </span>
    </div>
    
</div>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load widget_tweaks %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<div class="border border-3 border-dark rounded my-4 p-4">

    <!-- POST TITLE -->
    <h1>{{ post.title }}</h1>
    <p class="date text-muted text-right border-bottom pb-2 pr-1 mb-4">
        Posted {{ post.publish }} by {{ post.author }}
    </p>

    <!-- POST BODY -->
    <div class="px-1">{{ post.body | markdown }}</div>

    <!-- SHARE BUTTON -->
    <div class="text-right mb-4">
        <a href="{% url 'blog:post_share' post.id %}" class="text-decoration-none">
            <span class="bg-info px-3 py-2 rounded-pill text-light">Share this Post</span>
        </a>
    </div>

    <hr>

    <!-- SIMILAR POSTS SECTION -->
    <div class="mb-5">
        <h3>Similar Posts:</h3>
        <ul class="list-group w-50 text-wrap">

        {% for post in similar_posts %}
            <li class="list-group-item d-flex justify-content-between align-items-center p-0 ">
                <a  href="{{ post.get_absolute_url }}"
                    class="list-group-item text-success">
                    {{ post.title }}
                </a>
            </li>
        {% empty %}
            <li class="list-group-item d-flex justify-content-between align-items-center disabled">
                There are no similar posts yet.
            </li>
        {% endfor %}

        </ul>
    </div>

    <hr>

    <!-- POST COMMENTS TITLE -->
    {% with comments.count as total_comments %}
        <h3>
            {{ total_comments }} Comment{{ total_comments | pluralize }}:
        </h3>
    {% endwith %}

    <!-- POST COMMENTS LIST -->
    {% for comment in comments %}
        <div class="comment ">
            <figure class="d-inline-block w-50 border rounded px-3 py-2">
                <blockquote>
                  <p class="mb-0">{{ comment.body | linebreaks }}</p>
                </blockquote>
                <figcaption class="blockquote-footer text-muted">
                    written by <cite title="">{{ comment.name }}</cite> on {{ comment.created }}
                </figcaption>
            </figure>
        </div>
    
    {% empty %}
    <div class="mt-3">
        <p class="text-muted pl-2">No comments yet. Be the first!</p>
    </div>

    {% endfor %}

    <div class="mt-4">
        {% if new_comment %}
        <h2 class="text-success">Your comment has been added.</h2>

        {% else %}
            <hr>
            <h2>Add a new comment...</h2>
            <form class="d-inline-block pl-2 w-75" method="POST">
                {% csrf_token %}
                {{ form.errors }}

                <div class="mb-4">
                    {{ comment_form.name | add_class:"px-2" | append_attr:"placeholder=Name" }}
                
                    {{ comment_form.email | add_class:"px-2 mx-4" | append_attr:"placeholder=Email"}}
                </div>

                <div class="mb-3">
                    {{ comment_form.body | add_class:"p-2" | append_attr:"placeholder=Comment... "}}
                </div>

                <input type="submit" value="Add Comment" class="ml-2 pl-2">
            </form>

        {% endif %}
    </div>
    

</div>

{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul class="list-unstyled">
    {% for post in latest_posts %}
        <li class="pl-2">
            <a href="{{ post.get_absolute_url }}" class="light-blue">
                {{ post.title }}
            </a>
        </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}Bloggio{% endblock %}

{% block content %}
    <a href="/blog" class="text-decoration-none">
        <h1 class="display-4 text-info mt-4 pb-4 border-bottom border-secondary">
            Bloggio
        </h1>
    </a>    
    
    <div class="d-flex flex-column my-4">

        {% if tag %}
            <h3>Posts tagged with <span class="text-success">"{{ tag.name }}"</span></h3>
        {% endif %}

        {% for post in posts %}
            <div class="border rounded  border-secondary my-2 p-3">
                <h2 class="">
                    <a href="{{ post.get_absolute_url }}">
                        {{ post.title }}
                    </a>
                </h2>

                <p class="text-muted">
                    <span class="mr-2">{{ post.publish }} by {{ post.author }}.</span>
                    <span class="tags">
                        {% for tag in post.tags.all %}
                            <span class="badge bg-info text-wrap">
                                <a  href="{% url 'blog:post_list_by_tag' tag.slug %}"
                                    class="text-decoration-none text-light">
                                    {{ tag.name }}
                                </a>
                            </span>
                        {% endfor %}
                    </span>
                </p>
    
                {{  post.body | markdown | truncatewords_html:30 }}
            </div>
        {% endfor %}
    </div>

    {% include "./components/pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% load widget_tweaks %}

{% block title %}Share a post{% endblock %}

{% block content %}

<div class="mt-4">
    {% if sent %}
        <hr>
        <h1>Email Sent Successfully!</h1>
        <p class="pl-1">
            "{{ post.title }}" was successfully sent to <strong>{{ form.cleaned_data.to }}</strong>.
        </p>
        <hr>

    {% else %}
        <h1 class="mb-4">Share "{{ post.title }}" by Email!</h1>
        <form class="pl-4 py-3" method="POST">
            {% csrf_token %}
            {{ form.errors }}

            <div class="my-4">
               {{ form.name | add_class:"px-2" | append_attr:"placeholder=Name"}}
               {{ form.email  | add_class:"px-2 mx-3" | append_attr:"placeholder=Email"}}
            </div>

            <div class="mb-4">
                {{ form.to.label }}: 
                {{ form.to | add_class:"px-2" | append_attr:"placeholder=Recipient"}}
             </div>

             <div>
                {{ form.comments | add_class:"p-3" | append_attr:"placeholder=Comments..."}}
             </div>

            <input type="submit" value="Send Email" class="py-1 px-2 ml-3 mt-3">
        </form>
    {% endif %}
</div>

{% endblock %}

mysite/blog/templates/pagination.html
<div class="text-center">
    <div class="btn-group">
        <span class="step-links">
            {% if page.has_previous %}
                <span class="m-2 px-3 py-2 badge badge-pill badge-secondary">
                    <a  class="text-light text-decoration-none"
                        href="?page={{ page.previous_page_number }}">
                        <i class="fas fa-chevron-left pr-1"></i> Previous
                    </a>
                </span>
            {% endif %}
    
            <span class="px-3 py-1 border border-secondary border-2 rounded-pill current">
                Page {{ page.number }} of {{ page.paginator.num_pages }}
            </span>
    
            {% if page.has_next %}
                <span class="m-2 px-3 py-2 badge badge-pill badge-secondary">
                    <a  class="text-light text-decoration-none"
                        href="?page={{ page.next_page_number }}">
                        Next <i class="fas fa-chevron-right pl-1"></i>
                    </a>
                </span>
            {% endif %}
        </span>
    </div>
    
</div>